insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (1, 28, 48, 2.4);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (2, 8, 512, 3.8);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (3, 6, 256, 3.6);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (4, 18, 160, 4.0);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (5, 20, 160, 2.5);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (6, 6, 192, 1.8);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (7, 14, 160, 1.5);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (8, 20, 96, 2.0);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (9, 32, 144, 3.9);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (10, 20, 64, 1.0);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (11, 18, 48, 3.4);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (12, 28, 336, 2.5);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (13, 12, 352, 2.4);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (14, 30, 304, 1.6);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (15, 10, 336, 2.6);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (16, 10, 144, 3.1);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (17, 12, 512, 3.6);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (18, 12, 384, 3.9);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (19, 32, 496, 3.4);
insert into "INVENTORY"."It_products" ("P_ID", "ram(gb)", "storage(gb)", "processor(ghz)") values (20, 6, 416, 2.4);



insert into "INVENTORY"."Educational" ("P_ID", "level") values (61, 'pre_primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (62, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (63, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (64, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (65, 'primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (66, 'pre_primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (67, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (68, 'higher_secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (69, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (70, 'primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (71, 'primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (72, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (73, 'pre_primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (74, 'higher_secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (75, 'secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (76, 'primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (77, 'higher_secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (78, 'higher_secondary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (79, 'pre_primary');
insert into "INVENTORY"."Educational" ("P_ID", "level") values (80, 'primary');

insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (21, '09-Dec-2022', '10-Mar-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (22, '11-Feb-2022', '11-Apr-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (23, '13-Feb-2022', '06-Aug-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (24, '11-Oct-2022', '09-Feb-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (25, '14-Apr-2022', '11-Jul-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (26, '02-Nov-2022', '26-Feb-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (27, '10-Jan-2022', '16-Mar-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (28, '10-Jul-2022', '05-Apr-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (29, '12-Dec-2022', '10-Jun-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (30, '02-Nov-2022', '17-Feb-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (31, '06-Jun-2022', '15-Jan-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (32, '24-Feb-2022', '24-Feb-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (33, '30-Sep-2022', '20-Mar-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (34, '12-Aug-2022', '27-May-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (35, '11-Sep-2022', '21-Jul-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (36, '03-Jul-2022', '23-Jun-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (37, '14-Feb-2022', '14-Apr-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (38, '25-Jun-2022', '11-Jul-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (39, '04-Jun-2022', '22-May-2023');
insert into "INVENTORY"."Grocery" ("P_ID", "expiary_date", "production_date") values (40, '13-Sep-2022', '18-Apr-2023');

insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (41, 'red', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (42, 'red', 'pre_primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (43, 'white', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (44, 'black', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (45, 'blue', 'higher_secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (46, 'green', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (47, 'green', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (48, 'pink', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (49, 'orange', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (50, 'brown', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (51, 'purple', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (52, 'brown', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (53, 'red', 'higher_secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (54, 'purple', 'secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (55, 'brown', 'higher_secondary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (56, 'green', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (57, 'blue', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (58, 'red', 'pre_primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (59, 'gray', 'primary');
insert into "INVENTORY"."Toy" ("P_ID", "color", "level") values (60, 'yellow', 'higher_secondary');

ALTER TABLE "INVENTORY"."Fashion" 
MODIFY ("size" VARCHAR2(255))
ADD ("color" VARCHAR2(255));

insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (81, 'blue', 'XXS', 'viscose');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (82, 'green', 'L', 'cotton');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (83, 'green', 'S', 'acrylic');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (84, 'orange', 'XL', 'silk');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (85, 'purple', 'XXS', 'acrylic');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (86, 'green', 'XL', 'acrylic');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (87, 'black', 'M', 'nylon');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (88, 'black', 'XXS', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (89, 'gray', 'XXXXL', 'rayon');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (90, 'orange', 'S', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (91, 'white', 'XL', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (92, 'purple', 'XXXL', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (93, 'gray', 'XXXS', 'rayon');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (94, 'blue', 'XXXS', 'nylon');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (95, 'black', 'XXXXL', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (96, 'blue', 'L', 'rayon');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (97, 'black', 'XS', 'wool');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (98, 'yellow', 'M', 'acrylic');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (99, 'purple', 'XXL', 'spandex');
insert into "INVENTORY"."Fashion" ("P_ID", "color", "size", "made_of") values (100, 'blue', 'L', 'silk');