/*
 Navicat Premium Data Transfer

 Source Server         : Project_Inventory
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Schema         : INVENTORY

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 12/09/2023 19:42:45
*/


-- ----------------------------
-- Table structure for ORDERED_PRODUCTS
-- ----------------------------
DROP TABLE "INVENTORY"."ORDERED_PRODUCTS";
CREATE TABLE "INVENTORY"."ORDERED_PRODUCTS" (
  "TEMP_O_ID" NUMBER VISIBLE NOT NULL,
  "P_ID" NUMBER VISIBLE NOT NULL,
  "QUANTITY" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORDERED_PRODUCTS
-- ----------------------------
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('1', '46', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('1', '45', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('2', '71', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('205', '63', '5');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('206', '36', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('208', '63', '5');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('208', '46', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('229', '63', '1');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('229', '46', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('210', '63', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('211', '46', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('211', '45', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('212', '63', '5');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('212', '46', '5');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('213', '63', '4');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('213', '36', '4');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('214', '63', '4');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('215', '46', '6');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('216', '63', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('217', '63', '3');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('218', '63', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('2', '46', '1');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('2', '36', '13');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('2', '63', '4');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('3', '46', '2');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('3', '36', '45');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('3', '45', '12');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('225', '1', '1');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('225', '46', '1');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('225', '3', '1');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('228', '46', '3');
INSERT INTO "INVENTORY"."ORDERED_PRODUCTS" VALUES ('227', '46', '1');

-- ----------------------------
-- Primary Key structure for table ORDERED_PRODUCTS
-- ----------------------------
ALTER TABLE "INVENTORY"."ORDERED_PRODUCTS" ADD CONSTRAINT "SYS_C008044" PRIMARY KEY ("TEMP_O_ID", "P_ID");

-- ----------------------------
-- Checks structure for table ORDERED_PRODUCTS
-- ----------------------------
ALTER TABLE "INVENTORY"."ORDERED_PRODUCTS" ADD CONSTRAINT "SYS_C008042" CHECK ("TEMP_O_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "INVENTORY"."ORDERED_PRODUCTS" ADD CONSTRAINT "SYS_C008043" CHECK ("P_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
