insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (1, 'Amazon Echo', 'IT_PRODUCTS', 994199.29, 76, 159, 232);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (2, 'Kindle Paperwhite', 'IT_PRODUCTS', 822595.55, 646, 128, 190);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (3, 'Fire TV Stick', 'IT_PRODUCTS', 210220.82, 626, 233, 932);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (4, 'Apple MacBook Pro', 'IT_PRODUCTS', 870962.31, 617, 634, 148);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (5, 'Samsung Galaxy S20', 'IT_PRODUCTS', 539767.27, 81, 719, 191);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (6, 'Sony PlayStation 5', 'IT_PRODUCTS', 286784.58, 621, 652, 266);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (7, 'Bose QuietComfort 35', 'IT_PRODUCTS', 729043.24, 939, 368, 659);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (8, 'Fitbit Versa 2', 'IT_PRODUCTS', 175631.28, 311, 945, 326);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (9, 'DJI Mavic Air 2', 'IT_PRODUCTS', 206092.31, 857, 63, 492);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (10, 'Nintendo Switch', 'IT_PRODUCTS', 511300.18, 578, 520, 705);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (11, 'Microsoft Surface Pro', 'IT_PRODUCTS', 413519.87, 928, 501, 536);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (12, 'GoPro Hero 9', 'IT_PRODUCTS', 629563.94, 526, 200, 814);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (13, 'LG OLED TV', 'IT_PRODUCTS', 173975.22, 471, 113, 690);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (14, 'Canon EOS Rebel T7i', 'IT_PRODUCTS', 606924.56, 965, 557, 749);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (15, 'HP Pavilion Gaming Laptop', 'IT_PRODUCTS', 755803.27, 813, 564, 766);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (16, 'Anker PowerCore 10000', 'IT_PRODUCTS', 657698.87, 507, 757, 653);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (17, 'Razer DeathAdder Elite', 'IT_PRODUCTS', 530466.01, 521, 866, 888);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (18, 'Logitech MX Master 3', 'IT_PRODUCTS', 350928.03, 887, 257, 889);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (19, 'JBL Flip 5', 'IT_PRODUCTS', 113245.53, 383, 922, 298);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (20, 'Lenovo ThinkPad X1 Carbon', 'IT_PRODUCTS', 517471.5, 704, 812, 373);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (21, 'Organic bananas', 'GROCERY', 238.15, 111, 119, 333);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (22, 'Extra virgin olive oil', 'GROCERY', 147.92, 33, 319, 943);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (23, 'Free-range eggs', 'GROCERY', 474.81, 426, 894, 226);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (24, 'Almond milk', 'GROCERY', 423.2, 303, 219, 877);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (25, 'Whole wheat bread', 'GROCERY', 154.0, 755, 169, 713);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (26, 'Greek yogurt', 'GROCERY', 399.64, 243, 208, 310);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (27, 'Quinoa', 'GROCERY', 378.4, 55, 31, 479);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (28, 'Avocado', 'GROCERY', 451.64, 617, 853, 295);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (29, 'Spinach', 'GROCERY', 497.25, 721, 53, 504);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (30, 'Salmon fillets', 'GROCERY', 155.0, 305, 524, 258);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (31, 'Chickpeas', 'GROCERY', 408.98, 925, 941, 960);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (32, 'Almonds', 'GROCERY', 316.78, 10, 352, 667);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (33, 'Coconut water', 'GROCERY', 167.08, 229, 512, 957);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (34, 'Honey', 'GROCERY', 386.36, 93, 119, 799);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (35, 'Dark chocolate', 'GROCERY', 392.4, 512, 842, 830);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (36, 'Cauliflower rice', 'GROCERY', 397.03, 570, 969, 396);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (37, 'Protein bars', 'GROCERY', 374.71, 34, 736, 698);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (38, 'Frozen berries', 'GROCERY', 123.38, 269, 207, 185);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (39, 'Canned tuna', 'GROCERY', 330.38, 916, 54, 285);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (40, 'Granola bars', 'GROCERY', 495.33, 469, 273, 776);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (41, 'Action Figure', 'TOY', 1603.72, 647, 494, 327);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (42, 'Doll', 'TOY', 1794.97, 327, 320, 177);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (43, 'Board Game', 'TOY', 1012.17, 539, 946, 951);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (44, 'Puzzle', 'TOY', 1831.62, 85, 641, 617);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (45, 'Remote Control Car', 'TOY', 1228.23, 746, 959, 997);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (46, 'Building Blocks', 'TOY', 849.77, 684, 974, 587);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (47, 'Stuffed Animal', 'TOY', 1767.91, 318, 540, 545);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (48, 'Art Set', 'TOY', 1437.19, 809, 797, 620);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (49, 'Play-Doh Set', 'TOY', 902.18, 566, 247, 393);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (50, 'LEGO Set', 'TOY', 1059.4, 689, 296, 830);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (51, 'Barbie Doll', 'TOY', 1945.36, 72, 953, 504);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (52, 'Hot Wheels Car', 'TOY', 742.45, 275, 919, 695);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (53, 'Robot Toy', 'TOY', 738.62, 694, 813, 677);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (54, 'Outdoor Playset', 'TOY', 1766.45, 961, 863, 465);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (55, 'Toy Kitchen Set', 'TOY', 1156.33, 688, 370, 696);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (56, 'Toy Train Set', 'TOY', 1634.87, 24, 746, 351);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (57, 'Science Experiment Kit', 'TOY', 1379.39, 940, 108, 477);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (58, 'Toy Guitar', 'TOY', 1640.02, 380, 832, 652);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (59, 'Toy Drum Set', 'TOY', 1388.2, 259, 898, 833);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (60, 'Toy Tool Set', 'TOY', 1819.59, 377, 723, 570);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (61, 'Math Workbook', 'EDUCATIONAL', 8651.26, 87, 345, 928);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (62, 'Science Kit', 'EDUCATIONAL', 14247.95, 751, 590, 286);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (63, 'Language Learning Set', 'EDUCATIONAL', 9804.97, 831, 973, 524);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (64, 'History Textbook', 'EDUCATIONAL', 19490.58, 443, 900, 995);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (65, 'Art Supplies Set', 'EDUCATIONAL', 4261.88, 486, 810, 940);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (66, 'Coding Game', 'EDUCATIONAL', 13891.66, 671, 851, 741);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (67, 'Geography Puzzle', 'EDUCATIONAL', 1787.57, 345, 330, 426);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (68, 'Physics Experiment Kit', 'EDUCATIONAL', 2193.4, 396, 845, 688);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (69, 'Chemistry Lab Set', 'EDUCATIONAL', 1192.13, 142, 312, 201);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (70, 'Literature Anthology', 'EDUCATIONAL', 18155.3, 216, 53, 801);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (71, 'Music Instrument Set', 'EDUCATIONAL', 18015.95, 998, 969, 774);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (72, 'Robotics Kit', 'EDUCATIONAL', 7113.67, 863, 756, 417);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (73, 'Engineering Building Blocks', 'EDUCATIONAL', 11219.3, 733, 449, 788);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (74, 'Foreign Language Flashcards', 'EDUCATIONAL', 19883.93, 834, 440, 500);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (75, 'Biology Microscope', 'EDUCATIONAL', 1874.47, 445, 904, 853);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (76, 'Astronomy Telescope', 'EDUCATIONAL', 14463.88, 761, 298, 278);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (77, 'Writing Skills Workbook', 'EDUCATIONAL', 8729.93, 980, 587, 649);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (78, 'Critical Thinking Game', 'EDUCATIONAL', 12927.03, 524, 629, 260);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (79, 'Geology Exploration Kit', 'EDUCATIONAL', 4664.58, 771, 808, 744);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (80, 'Anatomy Model', 'EDUCATIONAL', 19674.58, 237, 238, 984);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (81, 'Women''s Floral Print Dress', 'FASHION', 12342.97, 194, 563, 476);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (82, 'Men''s Leather Wallet', 'FASHION', 18093.13, 119, 512, 1000);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (83, 'Makeup Brush Set', 'FASHION', 6736.15, 689, 70, 268);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (84, 'Hair Straightener', 'FASHION', 13232.31, 468, 713, 499);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (85, 'Women''s High Heels', 'FASHION', 10636.56, 815, 580, 139);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (86, 'Men''s Sports Watch', 'FASHION', 7256.0, 376, 480, 570);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (87, 'Facial Cleansing Brush', 'FASHION', 17060.65, 664, 263, 117);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (88, 'Perfume Gift Set', 'FASHION', 3460.69, 49, 301, 554);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (89, 'Women''s Designer Handbag', 'FASHION', 12218.9, 511, 855, 221);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (90, 'Men''s Grooming Kit', 'FASHION', 17036.98, 353, 142, 362);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (91, 'Nail Polish Set', 'FASHION', 10685.45, 463, 777, 427);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (92, 'Hair Dryer', 'FASHION', 16618.83, 295, 939, 217);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (93, 'Women''s Sunglasses', 'FASHION', 11603.85, 821, 591, 920);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (94, 'Men''s Cologne', 'FASHION', 18917.56, 989, 10, 904);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (95, 'Eyeshadow Palette', 'FASHION', 4668.76, 867, 562, 803);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (96, 'Hair Curling Iron', 'FASHION', 3276.02, 410, 264, 757);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (97, 'Women''s Ankle Boots', 'FASHION', 13819.86, 250, 592, 814);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (98, 'Men''s Shaving Razor', 'FASHION', 4839.0, 273, 615, 881);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (99, 'Lipstick Set', 'FASHION', 3311.89, 772, 33, 909);
insert into "INVENTORY"."Product" ("P_ID", "P_NAME", "TYPE", "PRICE", "REMAINING_ITEM", "SOLD_QUANTITY", "PER_UNIT_CHARGE") values (100, 'Face Mask Set', 'FASHION', 4719.56, 283, 617, 276);
