insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (28, 82, '27-Feb-2023', 4, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (31, 91, '22-Aug-2022', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (33, 42, '13-Jul-2023', 3, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (36, 51, '02-Jul-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 65, '23-Oct-2022', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (4, 62, '29-Apr-2023', 5, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 54, '03-May-2023', 3, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 24, '21-Oct-2022', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 96, '28-Apr-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 61, '11-Oct-2022', 2, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 98, '01-Jul-2023', 3, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (88, 80, '13-Feb-2023', 2, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 85, '28-Jan-2023', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 93, '04-Dec-2022', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 35, '09-Jan-2023', 5, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 92, '29-Nov-2022', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 12, '30-Jul-2023', 2, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (11, 85, '28-Oct-2022', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (67, 98, '26-Jul-2023', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (16, 12, '16-Jul-2023', 1, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 6, '26-Feb-2023', 4, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 75, '21-Sep-2022', 4, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (24, 4, '05-Aug-2023', 1, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (39, 89, '04-Nov-2022', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 10, '26-Oct-2022', 5, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (5, 91, '15-Nov-2022', 3, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 86, '06-May-2023', 1, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 16, '29-Jun-2023', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 68, '23-Jul-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 54, '10-Nov-2022', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (90, 46, '20-Nov-2022', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (95, 60, '26-Jul-2023', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 88, '27-Aug-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 95, '01-Oct-2022', 1, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 27, '17-Jun-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 47, '22-Nov-2022', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (42, 82, '18-May-2023', 3, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 97, '15-Jun-2023', 1, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 76, '02-Dec-2022', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 77, '07-Feb-2023', 4, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (12, 90, '12-Nov-2022', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (69, 12, '19-Jul-2023', 1, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 9, '16-Mar-2023', 2, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (96, 66, '27-Jan-2023', 4, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 14, '10-Jul-2023', 4, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (34, 18, '25-Jan-2023', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (11, 70, '08-Mar-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 90, '09-Jul-2023', 4, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 7, '29-Mar-2023', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 64, '03-Apr-2023', 1, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (88, 87, '20-Aug-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (36, 25, '15-Feb-2023', 5, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 31, '30-Oct-2022', 1, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (10, 61, '13-Mar-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 17, '12-Apr-2023', 1, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 40, '06-Nov-2022', 1, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (82, 84, '25-Jul-2023', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (80, 64, '03-Jan-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 12, '29-Nov-2022', 5, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 75, '25-Mar-2023', 5, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 10, '11-Oct-2022', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (9, 92, '30-Jul-2023', 4, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (20, 14, '13-Feb-2023', 1, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 27, '22-Jun-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (63, 25, '01-Oct-2022', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 54, '21-Jan-2023', 4, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (59, 9, '01-Oct-2022', 4, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 64, '18-Sep-2022', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 58, '01-Nov-2022', 5, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 86, '21-Dec-2022', 4, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 34, '01-Aug-2023', 5, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 3, '19-Dec-2022', 3, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (98, 99, '01-Aug-2023', 5, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (97, 43, '12-Feb-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (8, 96, '02-Jul-2023', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (48, 70, '22-Aug-2022', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (30, 33, '01-Feb-2023', 1, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 81, '25-Dec-2022', 4, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (70, 44, '16-Jan-2023', 5, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 63, '29-Jun-2023', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 83, '26-Oct-2022', 4, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 58, '11-Sep-2022', 3, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 28, '28-Jan-2023', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 98, '23-Sep-2022', 2, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (57, 59, '10-Feb-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 82, '23-Apr-2023', 2, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 53, '22-Jun-2023', 5, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (77, 37, '09-Nov-2022', 5, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (4, 80, '22-May-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (82, 76, '26-May-2023', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 98, '01-Dec-2022', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (96, 3, '13-Mar-2023', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (93, 22, '05-Oct-2022', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 16, '07-Dec-2022', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 76, '01-Mar-2023', 2, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (41, 18, '28-Sep-2022', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 64, '12-Jan-2023', 3, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 35, '09-Mar-2023', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 76, '28-Jan-2023', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (50, 64, '06-Sep-2022', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 74, '11-Apr-2023', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (54, 51, '17-Sep-2022', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 84, '21-Dec-2022', 3, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (79, 70, '01-Sep-2022', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 25, '31-Jan-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 13, '08-Dec-2022', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 80, '21-Apr-2023', 2, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 37, '05-Jun-2023', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 82, '02-Mar-2023', 5, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (23, 22, '07-Mar-2023', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 81, '27-Nov-2022', 3, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 22, '21-Jan-2023', 2, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 11, '10-Mar-2023', 4, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 44, '12-Mar-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (66, 3, '10-Nov-2022', 3, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 60, '30-Apr-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (99, 87, '09-May-2023', 1, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 21, '28-Dec-2022', 4, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 41, '12-Jul-2023', 4, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 19, '13-Sep-2022', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 91, '03-Feb-2023', 4, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 35, '15-Dec-2022', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (76, 77, '02-Oct-2022', 5, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 78, '30-Dec-2022', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (65, 34, '01-Feb-2023', 1, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 100, '22-Aug-2022', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 34, '21-Aug-2022', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 57, '01-May-2023', 5, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (20, 58, '20-Jul-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (31, 76, '24-Apr-2023', 3, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (32, 96, '01-Jun-2023', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (80, 36, '24-Jul-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (1, 82, '26-Dec-2022', 2, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 99, '06-Mar-2023', 2, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (5, 25, '25-Sep-2022', 2, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 9, '27-Jul-2023', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 44, '10-Jun-2023', 4, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 94, '21-Sep-2022', 5, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (15, 32, '26-May-2023', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (40, 79, '11-Sep-2022', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 49, '06-Aug-2023', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (30, 67, '18-Sep-2022', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 99, '07-Jan-2023', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 31, '22-Oct-2022', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 56, '11-Jan-2023', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (50, 65, '02-Apr-2023', 3, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (88, 52, '24-Jan-2023', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 18, '30-Oct-2022', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (7, 35, '12-Oct-2022', 4, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 78, '16-Jul-2023', 5, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (40, 11, '11-Dec-2022', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (79, 51, '31-Aug-2022', 4, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 30, '29-Aug-2022', 3, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 90, '15-Mar-2023', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (7, 75, '12-Jan-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (48, 2, '24-Nov-2022', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 91, '18-Nov-2022', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 28, '10-Jan-2023', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 85, '14-Sep-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (44, 23, '15-Nov-2022', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (10, 2, '09-Jun-2023', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 66, '08-Oct-2022', 5, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 5, '06-Aug-2023', 4, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (65, 55, '15-Jun-2023', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 73, '21-Mar-2023', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 57, '17-Jul-2023', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (9, 21, '05-Sep-2022', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (82, 13, '18-Dec-2022', 4, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 29, '09-Feb-2023', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (15, 100, '01-Nov-2022', 4, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 93, '30-Jan-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (31, 49, '01-Aug-2023', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 77, '09-Oct-2022', 4, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 64, '02-Jan-2023', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (54, 99, '26-Jan-2023', 3, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (25, 47, '16-Dec-2022', 1, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 58, '16-Nov-2022', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 1, '16-Oct-2022', 3, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 45, '23-Sep-2022', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (25, 56, '30-Sep-2022', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (36, 67, '29-Aug-2022', 3, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (11, 57, '09-Dec-2022', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (8, 10, '08-May-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 83, '03-Oct-2022', 4, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 68, '04-Nov-2022', 3, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 68, '10-May-2023', 5, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 94, '12-Mar-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (42, 50, '11-Aug-2023', 2, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (42, 30, '20-Dec-2022', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 46, '29-Oct-2022', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (48, 72, '23-Feb-2023', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 92, '05-Sep-2022', 5, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 59, '08-Jul-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (36, 76, '10-Mar-2023', 3, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 66, '08-May-2023', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 14, '20-Sep-2022', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 94, '27-Apr-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 73, '08-Nov-2022', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (86, 38, '08-Sep-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (40, 13, '30-Apr-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 92, '23-Jun-2023', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (51, 36, '05-Apr-2023', 5, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (63, 71, '20-Sep-2022', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (8, 90, '16-Sep-2022', 2, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (18, 51, '04-Sep-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 1, '15-Nov-2022', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 81, '14-Oct-2022', 4, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 74, '27-Oct-2022', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (34, 16, '23-Sep-2022', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 4, '06-Jul-2023', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 96, '28-Mar-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (65, 74, '28-Aug-2022', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (75, 79, '12-Aug-2023', 2, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 6, '14-Nov-2022', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 17, '20-Dec-2022', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 83, '03-Nov-2022', 3, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (7, 25, '28-Aug-2022', 2, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 5, '03-Apr-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (40, 77, '13-May-2023', 5, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 64, '16-Jun-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (11, 41, '15-Jan-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 66, '19-Sep-2022', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (77, 94, '17-Sep-2022', 2, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (69, 45, '23-Jan-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 39, '05-Jun-2023', 3, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (17, 44, '22-Sep-2022', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 41, '15-Jan-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 32, '27-Jun-2023', 2, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (46, 36, '12-May-2023', 2, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 18, '14-Dec-2022', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (69, 11, '15-Jun-2023', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 16, '17-Dec-2022', 3, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 68, '19-Sep-2022', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 86, '18-Sep-2022', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 98, '07-Nov-2022', 3, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 62, '12-Jul-2023', 2, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 63, '01-Dec-2022', 4, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 78, '17-Mar-2023', 3, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 55, '11-Jun-2023', 2, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (90, 1, '06-Sep-2022', 3, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 6, '21-Aug-2022', 5, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 53, '19-Jan-2023', 2, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (76, 84, '17-Mar-2023', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 23, '21-May-2023', 2, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 60, '10-Mar-2023', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 81, '13-Aug-2023', 1, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (19, 91, '27-Dec-2022', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 90, '26-Apr-2023', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (50, 64, '05-Apr-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 19, '02-Sep-2022', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 63, '25-Jun-2023', 2, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (29, 97, '29-Jul-2023', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (95, 10, '04-Mar-2023', 5, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 75, '26-Nov-2022', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 99, '30-Jul-2023', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 45, '01-Nov-2022', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 93, '23-Jul-2023', 3, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (12, 29, '25-Apr-2023', 4, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 45, '28-May-2023', 1, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 37, '19-Oct-2022', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 54, '18-May-2023', 1, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (24, 52, '04-Jun-2023', 3, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 92, '30-Jan-2023', 4, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 32, '14-Oct-2022', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (69, 96, '17-Dec-2022', 2, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 77, '07-Dec-2022', 5, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (46, 71, '08-Jul-2023', 5, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (86, 57, '11-Apr-2023', 1, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 63, '17-Jul-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (48, 26, '09-Oct-2022', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 38, '29-Jul-2023', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 32, '15-Aug-2023', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 6, '17-May-2023', 4, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (5, 64, '24-Apr-2023', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (90, 68, '14-Nov-2022', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (25, 4, '08-Sep-2022', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 16, '09-Jun-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 83, '08-May-2023', 4, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 45, '14-Jul-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 9, '12-Aug-2023', 2, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (39, 34, '22-Mar-2023', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 11, '05-Aug-2023', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 18, '21-Feb-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 15, '12-Apr-2023', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (90, 30, '25-Aug-2022', 2, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (29, 64, '11-Jan-2023', 5, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (77, 59, '28-Dec-2022', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 70, '13-Jan-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (65, 67, '28-Feb-2023', 1, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (54, 70, '28-Jul-2023', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 37, '23-Aug-2022', 2, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 98, '10-Jul-2023', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 20, '08-Sep-2022', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (5, 85, '21-Feb-2023', 3, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (94, 77, '06-Mar-2023', 5, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 68, '20-Jun-2023', 4, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 16, '27-Mar-2023', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (11, 43, '06-Apr-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 30, '18-May-2023', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (82, 23, '13-Apr-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (61, 16, '05-Oct-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 3, '20-Feb-2023', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 70, '02-May-2023', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 17, '07-Dec-2022', 3, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (28, 52, '13-Feb-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 98, '05-Jun-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (94, 43, '30-Dec-2022', 1, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 54, '24-Apr-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (97, 46, '01-Dec-2022', 1, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (16, 75, '12-Feb-2023', 4, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 5, '27-Jul-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 94, '05-Mar-2023', 1, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (67, 88, '22-Aug-2022', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 26, '13-Jun-2023', 5, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 63, '16-Sep-2022', 5, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (33, 18, '17-Jul-2023', 2, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (20, 12, '16-Mar-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 68, '31-May-2023', 5, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (72, 10, '30-Apr-2023', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 50, '05-Aug-2023', 3, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 65, '31-Mar-2023', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (98, 97, '30-Jul-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 57, '28-Dec-2022', 4, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (87, 30, '22-Mar-2023', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 24, '21-May-2023', 2, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 11, '10-Nov-2022', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (76, 46, '15-Aug-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (25, 76, '13-Oct-2022', 2, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 17, '06-Apr-2023', 2, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (6, 90, '31-Oct-2022', 5, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 45, '13-Feb-2023', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (67, 81, '22-Jul-2023', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (17, 6, '13-Feb-2023', 1, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 80, '17-Dec-2022', 4, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (97, 98, '10-Oct-2022', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (10, 34, '12-Oct-2022', 5, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (88, 76, '30-Nov-2022', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 8, '02-Jun-2023', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 95, '06-May-2023', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (46, 31, '17-Jul-2023', 2, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (24, 56, '20-Aug-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 76, '05-Jan-2023', 5, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (1, 89, '08-Oct-2022', 1, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (93, 29, '12-Apr-2023', 2, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 44, '15-Feb-2023', 3, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 94, '23-Nov-2022', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 36, '04-Aug-2023', 5, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (25, 57, '04-Oct-2022', 4, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 76, '10-Jan-2023', 2, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (41, 5, '15-Dec-2022', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (19, 22, '27-Dec-2022', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (80, 7, '21-Aug-2022', 2, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (3, 72, '12-Sep-2022', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (95, 11, '08-Oct-2022', 1, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (90, 21, '12-Mar-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (4, 88, '12-Nov-2022', 3, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 42, '13-Nov-2022', 2, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 85, '17-Jan-2023', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (77, 42, '04-Feb-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 90, '07-Jan-2023', 3, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 2, '01-Nov-2022', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 69, '04-Jan-2023', 4, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (33, 53, '29-Apr-2023', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 44, '29-Jul-2023', 3, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 79, '03-Jun-2023', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (33, 96, '16-Mar-2023', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (24, 28, '06-Feb-2023', 3, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (66, 91, '16-Nov-2022', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (32, 60, '26-Jul-2023', 1, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 81, '09-Nov-2022', 1, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 33, '24-May-2023', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (33, 44, '14-Dec-2022', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (32, 61, '24-Jun-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (95, 96, '10-Dec-2022', 4, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (98, 72, '16-Sep-2022', 2, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 90, '21-Aug-2022', 1, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (42, 59, '10-Jun-2023', 3, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 33, '19-Apr-2023', 1, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 9, '16-Dec-2022', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (41, 33, '20-Sep-2022', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 93, '10-Nov-2022', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (10, 23, '16-Jul-2023', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 10, '28-Jan-2023', 2, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 80, '15-Jul-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 32, '19-Feb-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (15, 31, '24-Dec-2022', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 3, '19-Jun-2023', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 91, '19-Feb-2023', 4, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 16, '06-Mar-2023', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (20, 63, '16-Aug-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 24, '26-Dec-2022', 3, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (93, 53, '20-Jul-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (15, 86, '03-Jul-2023', 1, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (29, 46, '06-Aug-2023', 4, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (29, 75, '07-Dec-2022', 2, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (14, 75, '26-Nov-2022', 4, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (23, 57, '14-Jun-2023', 1, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (79, 62, '25-Aug-2022', 2, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (95, 87, '04-Jul-2023', 5, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (67, 67, '22-Jun-2023', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (50, 67, '17-Jul-2023', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (1, 14, '30-Aug-2022', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (100, 54, '25-Mar-2023', 2, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 25, '27-Jun-2023', 4, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 2, '26-Jun-2023', 4, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 81, '14-Jun-2023', 4, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 61, '21-Mar-2023', 2, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 31, '05-Nov-2022', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (97, 46, '16-Jun-2023', 4, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (94, 62, '13-May-2023', 1, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 80, '05-Dec-2022', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 11, '14-Jun-2023', 4, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 65, '01-Jul-2023', 4, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (67, 95, '15-Sep-2022', 2, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (73, 6, '01-Oct-2022', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 15, '31-Jan-2023', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 65, '27-Oct-2022', 3, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 56, '16-Jul-2023', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (55, 75, '12-Jan-2023', 5, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 74, '24-Apr-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 59, '02-Feb-2023', 2, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 5, '01-Mar-2023', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (86, 69, '28-May-2023', 1, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (82, 5, '21-Jun-2023', 4, 'This product is worth every penny!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 13, '09-Dec-2022', 4, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 24, '30-May-2023', 4, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (65, 67, '06-Apr-2023', 5, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (98, 47, '20-Apr-2023', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 28, '25-Jan-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (80, 84, '10-Jun-2023', 5, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (81, 14, '05-Feb-2023', 1, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (23, 49, '23-Dec-2022', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (50, 24, '13-Dec-2022', 1, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (68, 48, '29-Apr-2023', 1, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (91, 68, '10-Sep-2022', 4, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (57, 82, '03-Sep-2022', 5, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (10, 16, '01-Mar-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (26, 10, '07-Apr-2023', 5, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (78, 94, '24-Mar-2023', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (96, 1, '29-Sep-2022', 4, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (71, 90, '06-Jun-2023', 3, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 14, '23-Feb-2023', 1, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 78, '16-Jun-2023', 2, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (20, 5, '05-Jun-2023', 1, 'I''m so impressed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 95, '26-Mar-2023', 5, 'I can''t imagine my life without this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 39, '07-Oct-2022', 4, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 18, '12-May-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (52, 55, '02-Jul-2023', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (64, 97, '12-Dec-2022', 3, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (44, 53, '01-Jul-2023', 4, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (37, 86, '30-Jul-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 67, '22-Jul-2023', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (19, 7, '14-Jan-2023', 1, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (27, 3, '03-Jul-2023', 3, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 98, '15-Feb-2023', 3, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (39, 93, '20-May-2023', 1, 'I''m obsessed with this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (23, 12, '03-Jun-2023', 1, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 92, '18-May-2023', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 51, '19-Jun-2023', 3, 'I can''t get enough of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (47, 64, '09-Jun-2023', 5, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 45, '18-Jun-2023', 2, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 98, '11-Sep-2022', 4, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (40, 19, '15-Jan-2023', 2, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (77, 12, '27-Sep-2022', 4, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (60, 18, '02-Nov-2022', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (92, 70, '11-Aug-2023', 5, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (70, 77, '11-Mar-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (2, 70, '01-Jun-2023', 5, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 68, '04-Oct-2022', 5, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (74, 52, '09-Apr-2023', 3, 'This product is a must-have!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (93, 76, '08-May-2023', 4, 'I can''t stop raving about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (93, 79, '27-Oct-2022', 2, 'This product is a game-changer!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (38, 13, '10-Oct-2022', 2, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (58, 28, '15-Feb-2023', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 93, '02-Nov-2022', 5, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (43, 84, '02-Oct-2022', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (62, 81, '12-Jul-2023', 1, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (89, 11, '18-May-2023', 5, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (53, 24, '24-Nov-2022', 1, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (21, 2, '04-Nov-2022', 3, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (63, 32, '13-May-2023', 5, 'This product is a dream come true!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 9, '13-Sep-2022', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (85, 67, '05-Sep-2022', 1, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 14, '12-Nov-2022', 1, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (35, 41, '01-Apr-2023', 3, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (56, 70, '07-Jun-2023', 5, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (63, 84, '21-Dec-2022', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (45, 12, '24-Sep-2022', 4, 'I highly recommend this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (49, 40, '17-May-2023', 5, 'I''m blown away by this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (75, 19, '09-Jun-2023', 4, 'I''ve never been happier with a product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (70, 33, '02-Aug-2023', 2, 'The design of this product is beautiful!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (22, 89, '07-Mar-2023', 2, 'This product is top-notch!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (48, 93, '06-Aug-2023', 1, 'The quality of this product is outstanding!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (63, 2, '03-May-2023', 2, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (24, 6, '22-Oct-2022', 2, 'This product is pure perfection!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (7, 81, '17-Aug-2023', 4, 'I''m in awe of this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (84, 33, '08-Mar-2023', 4, 'I love everything about this product!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (83, 5, '08-Apr-2023', 4, 'This product is amazing!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (13, 58, '26-Jun-2023', 3, 'This product exceeded my expectations!');
insert into "INVENTORY"."REVIEWS" ("C_ID", "P_ID", "REVIEW_DATE", "RATING", "COMMENTS") values (88, 78, '14-May-2023', 1, 'I''m in awe of this product!');
